# # title: iamcamilo - Camilo Munoz
# url: "https://iamcamilo.me"
# baseurl:
# google_analytics_key:
# # google_maps_javascript_api_key:
# # disqus_shortname:
#
# # Default description in social shares for the jekyll-seo-tag gem
# description: Camilo Munoz is a UI & UX Designer. He can do Web, App and Brand Design.
#
# # Author details for the jekyll-seo-tag gem
# author: iamcamilo
#   # name: Camilo Munoz Donoso
#   email: hello@iamcamilo.me
#   twitter: # twitter username without the @ symbol

title: iamcamilo - Camilo Muñoz Donoso - Designer and Front-end Developer from Chile.
email: hello@iamcamilo.me
description: > # this means to ignore newlines until "baseurl:"
  My name is Camilo Muñoz, I'm a Designer and Front-end Developer from Chile, who since I discovered the digital world, I immediately fell in love with all the strength that intangible products can have. I’ve been designing/building websites, apps and brands for over 6 years, always making decisions tailored to the user's needs.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# SCSS Setup
sass:
  sass_dir: _scss
  style: :compressed

# Collections
collections:
  services:
  about:
  portfolio:

# Gems

gems:
-  jekyll-autoprefixer
